name: Create and publish a Docker image to ghcr.io

on:
  push:
    tags:
      - "*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: hoppscotch/hoppscotch

      - name: Update Proxy url and enable
        run: |
          sed -i "s|proxy.hoppscotch.io|pm-p.develop.gs|g"  ./packages/hoppscotch-common/src/newstore/settings.ts
          sed -i "s|default: \"browser\"|default: \"proxy\"|g"  ./packages/hoppscotch-selfhost-web/src/main.ts
          cp .env.example .env
          sed -i '/^FROM base_builder as sh_admin_builder/,$d' ./prod.Dockerfile
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v4
      #   with:
      #     images: ghcr.io/greenstep-infra/hoppscotch

      - name: Build and push the frontend image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./prod.Dockerfile
          target: app
          push: true
          platforms: |
            linux/amd64
            linux/arm64
          tags: |
            ghcr.io/greenstep-infra/hoppscotch-frontend:latest
            ghcr.io/greenstep-infra/hoppscotch-frontend:${{ github.ref_name }}